### ISSUE TITLE
line 46 syntax error 

### ISSUE THREAD

**Issue by KittenOnCatnip** [raandoom/blender_export_tmf#3]
I am using blender 2.79 and i get a syntax error on line 46 when trying to run or install the script.

![image](https://user-images.githubusercontent.com/25055405/221388227-0bff36e4-82ea-4701-9180-6137c2a14b30.png)

![image](https://user-images.githubusercontent.com/25055405/221388292-44fc2219-ee7f-4045-ae4b-216d2aae6a43.png)

**Comment by raandoom** [comment]
@KittenOnCatnip i cant confirm it. It is very stable script for very stable old version. I don't know why you have such issue.
Anyway, why did you use such old version of blender, you can use the latest one.
But if you want to use 2.79, maybe try to install it, not running portable one.

**Comment by KittenOnCatnip** [comment]
i was watching a tutorial and he said you needed a specific version to use the script but apparently he was wrong.
